; Proteus code, 7SD
CODE SEGMENT
    
START:
 MOV AL, 080H
 OUT 0F6H, AL ; CR REGISTER ADDRESS = 0F6H, VALUE = 080H
 
X:
  MOV AL, 0C0H ;DISPLAYING '0''
  OUT 0F0H,AL ; PORT A ADDRESS = 0F0H 
   
  MOV AL, 0C0H ;DISPLAYING '0'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
  
  MOV AL, 0C0H ;DISPLAYING '0'
  OUT 0F4H,AL ; PORT C ADDRESS = 0F4H
  
  MOV CX, 0FFFFH ;DELAY
  L1: LOOP L1 
  
  MOV AL, 0F9H ;DISPLAYING '1''
  OUT 0F0H,AL ; PORT A ADDRESS = 0F0H 
   
  MOV AL, 0F9H ;DISPLAYING '1'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
  
  MOV AL, 0F9H ;DISPLAYING '1'
  OUT 0F4H,AL ; PORT C ADDRESS = 0F4H
  
  MOV CX, 0FFFFH ;DELAY
  L2: LOOP L2   
  
  MOV AL, 0A4H ;DISPLAYING '2''
  OUT 0F0H,AL ; PORT A ADDRESS = 0F0H 
   
  MOV AL, 0A4H ;DISPLAYING '2'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
  
  MOV AL, 0A4H ;DISPLAYING '2'
  OUT 0F4H,AL ; PORT C ADDRESS = 0F4H
  
  MOV CX, 0FFFFH ;DELAY
  L3: LOOP L3 
  
  MOV AL, 0B0H ;DISPLAYING '3''
  OUT 0F0H,AL ; PORT A ADDRESS = 0F0H 
   
  MOV AL, 0B0H ;DISPLAYING '3'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H       
  
  MOV AL, 0B0H ;DISPLAYING '3''
  OUT 0F4H,AL ; PORT C ADDRESS = 0F4H
  
  MOV CX, 0FFFFH ;DELAY
  L4: LOOP L4
  
  MOV AL, 099H ;DISPLAYING '4'
  OUT 0F0H,AL ; PORT A ADDRESS = 0F0H 
   
  MOV AL, 099H ;DISPLAYING '4'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H   
  
  MOV AL, 099H ;DISPLAYING '4'
  OUT 0F4H,AL ; PORT C ADDRESS = 0F4H
  
  MOV CX, 0FFFFH ;DELAY
  L5: LOOP L5  
  
  MOV AL, 092H ;DISPLAYING '5'
  OUT 0F0H,AL ; PORT A ADDRESS = 0F0H 
   
  MOV AL, 092H ;DISPLAYING '5'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
   
  MOV AL, 092H ;DISPLAYING '5'
  OUT 0F4H,AL ; PORT B ADDRESS = 0F4H
  
  MOV CX, 0FFFFH ;DELAY
  L6: LOOP L6  
  
  MOV AL, 0A0H ;DISPLAYING '6'
  OUT 0F0H,AL ; PORT A ADDRESS = 0F0H 
   
  MOV AL, 0A0H ;DISPLAYING '6'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
   
  MOV AL, 0A0H ;DISPLAYING '6'
  OUT 0F4H,AL ; PORT B ADDRESS = 0F4H
  
  MOV CX, 0FFFFH ;DELAY
  L7: LOOP L7  
  
  MOV AL, 0F8H ;DISPLAYING '7'
  OUT 0F0H,AL ; PORT A ADDRESS = 0F0H 
   
  MOV AL, 0F8H ;DISPLAYING '7'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
   
  MOV AL, 0F8H ;DISPLAYING '7'
  OUT 0F4H,AL ; PORT B ADDRESS = 0F4H
  
  MOV CX, 0FFFFH ;DELAY
  L8: LOOP L8  
  
  MOV AL, 080H ;DISPLAYING '8'
  OUT 0F0H,AL ; PORT A ADDRESS = 0F0H 
   
  MOV AL, 080H ;DISPLAYING '8'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
   
  MOV AL, 080H ;DISPLAYING '8'
  OUT 0F4H,AL ; PORT B ADDRESS = 0F4H
  
  MOV CX, 0FFFFH ;DELAY
  L9: LOOP L9
  
  MOV AL, 090H ;DISPLAYING '9'
  OUT 0F0H,AL ; PORT A ADDRESS = 0F0H 
   
  MOV AL, 090H ;DISPLAYING '9'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
   
  MOV AL, 090H ;DISPLAYING '9'
  OUT 0F4H,AL ; PORT B ADDRESS = 0F4H
  
  MOV CX, 0FFFFH ;DELAY
  L10: LOOP L10
               
             
  
  
  
  
JMP X

CODE ENDS
END