; Proteus code, 7SD
CODE SEGMENT
    
START:
 MOV AL, 080H
 OUT 0F6H, AL ; CR REGISTER ADDRESS = 0F6H, VALUE = 080H
 
X:
  MOV AL, 0E0H ;DISPLAYING 'J'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
  
  MOV CX, 0FFFFH ;DELAY
  L1: LOOP L1
  
  MOV AL, 090H ;DISPLAYING '9'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
  
  MOV CX, 0FFFFH ;DELAY
  L2: LOOP L2
  
  MOV AL, 080H ;DISPLAYING 'B'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
  
  MOV CX, 0FFFFH ;DELAY
  L3: LOOP L3
  
  MOV AL, 0FFH ;DISPLAYING 'OFF'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
  
  MOV CX, 0FFFFH ;DELAY
  L7: LOOP L7
  
  MOV AL, 0C0H ;DISPLAYING '0'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
  
  MOV CX, 0FFFFH ;DELAY
  L4: LOOP L4
  
  MOV AL, 089H ;DISPLAYING 'H'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
  
  MOV CX, 0FFFFH ;DELAY
  L5: LOOP L5
  
  MOV AL, 0B0H ;DISPLAYING '3'
  OUT 0F2H,AL ; PORT B ADDRESS = 0F2H 
  
  MOV CX, 0FFFFH ;DELAY
  L6: LOOP L6
  
  
  
  
JMP X

CODE ENDS
END